---
title: "Providence"
author: "Zhengkai Fu"
date: "21/05/2020"
output: pdf_document
---

```{r library, message = FALSE, warning = FALSE}
library(RSocrata)
library(tidyverse)
```
# COVID 19

# Providence Crime
## Load crime data
```{r get Providence data}
providence <- read.socrata(
  "https://data.providenceri.gov/resource/rz3y-pz8v.csv",
  app_token = "hPU78MH7zKApdpUv4OVCInPOQ")

head(providence)

# add date
providence <- providence %>%
  mutate(date = substr(reported_date, start = 1, stop = 10)) %>%
  mutate(y_month  = substr(reported_date, start = 1, stop = 7))

# extract most vague name of crime
providence <- providence %>%
  separate(offense_desc, c("crime", "detail_crime"), sep = ",")

```

## Overview of crime
```{r summary}
# summary of all crime
providence_summary <- providence %>%
  group_by(crime) %>%
  summarise(number_of_crime = n()) %>%
  arrange(desc(number_of_crime))

providence_summary

providence %>%
  filter(crime %in% head(providence_summary$crime, 5)) %>%
  ggplot(aes(x=crime)) +
  geom_bar()

# top 5 crime over time
# monthly
# not too many months anyways
providence %>%
  select(y_month, crime) %>%
  filter(crime %in% head(providence_summary$crime, 5)) %>% 
  count(y_month, crime) %>%
  ggplot(aes(y_month, n, group = crime, fill = crime)) +
  geom_area(size = 0.01, alpha = 0.5) + 
  scale_fill_brewer(palette = "Set1", breaks = rev(levels(providence_summary$OFFENSE_DESCRIPTION[1:5]))) +
  ggtitle("Frequency of top 5 crime in Providence")

# daily
```
